/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieDetails200GenresItem } from './movieDetails200GenresItem';
import type { MovieDetails200ProductionCompaniesItem } from './movieDetails200ProductionCompaniesItem';
import type { MovieDetails200ProductionCountriesItem } from './movieDetails200ProductionCountriesItem';
import type { MovieDetails200SpokenLanguagesItem } from './movieDetails200SpokenLanguagesItem';

export type MovieDetails200 = {
  adult?: boolean;
  backdrop_path?: string;
  belongs_to_collection?: unknown;
  budget?: number;
  genres?: MovieDetails200GenresItem[];
  homepage?: string;
  id?: number;
  imdb_id?: string;
  original_language?: string;
  original_title?: string;
  overview?: string;
  popularity?: number;
  poster_path?: string;
  production_companies?: MovieDetails200ProductionCompaniesItem[];
  production_countries?: MovieDetails200ProductionCountriesItem[];
  release_date?: string;
  revenue?: number;
  runtime?: number;
  spoken_languages?: MovieDetails200SpokenLanguagesItem[];
  status?: string;
  tagline?: string;
  title?: string;
  video?: boolean;
  vote_average?: number;
  vote_count?: number;
};
